ktor:
  deployment:
    port: 8080
  application:
    modules:
      - com.estoque.HttpKt.configureHttp
      - com.estoque.SerializationKt.configureSerialization
      - com.estoque.RoutingKt.configureRouting
